version: '3'
services:
    storage:
        image: mongo:latest
        ports:
            - '27018:27017'
        container_name: storage
        volumes: 
            - ./MongoImage/init-mongo-user.js:/docker-entrypoint-initdb.d/init-mongo-user.js:ro
            - ./MongoImage/data:/data/db
    ai:
        restart: always
        build:
            context: ./pyserver
            dockerfile: Dockerfile
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.2"
                    memory: 1G
        expose:
            - '5000'
        container_name: ai            
        volumes:
            - ./FileBank/models/training:/app/FileBank/models/training
            - ./FileBank/models/trained:/app/FileBank/models/trained            
    app:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        env_file: config/docker.env
        ports: 
            - '3100:3030'
        depends_on:
            - "storage"            
            - "ai"
        links:
            - "storage"            
            - "ai"
        volumes:
            - ./FileBank/models/training:/usr/src/app/FileBank/models/training
            - ./FileBank/models/trained:/usr/src/app/FileBank/models/trained            
